# Generated by Django 3.1.6 on 2021-02-12 16:24

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', ckeditor.fields.RichTextField()),
                ('likes', models.IntegerField(default=0, verbose_name='Likes')),
                ('publicado_em', models.DateTimeField(blank=True, null=True, verbose_name='Publicado em')),
                ('rascunho', models.BooleanField(default=True, verbose_name='Rascunho?')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_posts', related_query_name='rqn_posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
